### ISSUE TITLE
Ошибка Too few arguments to function PlgJshoppingproductsWt_jshopping_schema_org::onBeforeDisplayProductListView()

### ISSUE THREAD

**Issue by zedkam** [sergeytolkachyov/WT-JoomShopping-Schema.org#1]
При работе плагина возникает ошибка на листинге товаров Too few arguments to function PlgJshoppingproductsWt_jshopping_schema_org::onBeforeDisplayProductListView(), 1 passed in /var/www/****/data/www/*****/libraries/joomla/event/event.php on line 70 and exactly 2 expected

**Comment by sergeytolkachyov** [comment]
Какая версия JoomShopping? В ядре JoomShopping 4.18.x в этом триггере везде 2 параметра. 1 параметр в версиях 4.17.х и более ранних. Обновите JoomShopping.

**Comment by zedkam** [comment]
Joomshoppimg 4.15 из за этого наверное

**Comment by sergeytolkachyov** [comment]
> Joomshoppimg 4.15 из за этого наверное
Да, я проверял версии - с версии 4.18.х передаются 2 аргумента, до этой версии - только 1, а в плагине требуется 2. Поэтому и возникает ошибка "слишком много аргументов в функции".

**Comment by sergeytolkachyov** [comment]
Удалось решить проблему? Закрываю ишью?

**Comment by zedkam** [comment]
> 
> 
> Удалось решить проблему? Закрываю ишью?

Да, все работает. Благодарю!
