### ISSUE TITLE
Предупреждения в плагине

### ISSUE THREAD

**Issue by kosh2323** [sergeytolkachyov/WT-JoomShopping-Schema.org#2]
Здравствуйте Сергей. После установки плагина на сайте вижу предупреждения

Warning: Undefined property: Joomla\Component\Jshopping\Site\Table\ProductTable::$weight in SITE\plugins\jshoppingproducts\wt_jshopping_schema_org\wt_jshopping_schema_org.php on line 128

Joomla 4.2.2
Joomshopping 5.0.7
PHP 8.1

**Comment by sergeytolkachyov** [comment]
Здравствуйте. Значит у товара не заполнен вес.

**Comment by kosh2323** [comment]
Вес заполнил, в настройках как в списке товаров, так и в карточке товара установлено "показать вес", но предупреждения все равно есть

Warning: Undefined property: stdClass::$weight in \plugins\jshoppingproducts\wt_jshopping_schema_org\wt_jshopping_schema_org.php on line 286

Warning: Undefined property: stdClass::$weight in \plugins\jshoppingproducts\wt_jshopping_schema_org\wt_jshopping_schema_org.php on line 286

**Comment by sergeytolkachyov** [comment]
Исправлено в версии 1.1.4

**Comment by kosh2323** [comment]
Здравствуйте, Сергей, установил новую версию, предупреждений и ошибок не выдается. Спасибо за оперативность, Вы молодец.
